---
name: Build mods

on:
  workflow_dispatch:
    inputs:
      mods:
        type: string
        description: mod names to build
  push:
    paths:
      - "sources/*"
    branches:
      - main
  pull_request:

jobs:
  builds:
    name: Assemble build matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.builds.outputs.matrix }}
      mods: ${{ steps.builds.outputs.mods }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Get changed files
        if: ${{ github.event_name }} == "push"
        id: changed_files_action
        uses: tj-actions/changed-files@v45
        with:
          files: sources/*
      - name: Assemble build matrix
        id: builds
        run: |
          # Figure out which manifests need building
          if [[ "${{ github.event_name }}" == "push" || "${{ github.event_name }}" == "pull_request" ]]; then
            export MODS="${{ steps.changed_files_action.outputs.all_changed_files }}"
          elif [[ "${{ inputs.mods }}" != "" ]]; then
            export MODS="${{ inputs.mods }}"
          fi
          echo "::group::Matrix"
          export MATRIX=$(python3 generate_build_matrix.py)
          echo "MATRIX=$MATRIX" >> $GITHUB_OUTPUT
          echo $MATRIX | jq
          echo "::endgroup::"
          echo "::group::Mods"
          export MODS=$(echo $MATRIX | jq '.[].name' | uniq | jq -crn '[ { "name": inputs } ]')
          echo "MODS=$MODS" >> $GITHUB_OUTPUT
          echo $MODS | jq
          echo "::endgroup::"

  build-mod:
    name: ${{ matrix.target.name }}
    needs: builds
    strategy:
      matrix:
        target: ${{ fromJson(needs.builds.outputs.matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Build ${{ matrix.target.name }}
        uses: ${{ github.repository_owner }}/${{ github.repository }}/.github/workflows/build-mod.yml@main
        with:
          name: ${{ matrix.target.name }}
          runner: ${{ matrix.target.runner }}

  merge-artifacts:
    name: Merge artifacts for ${{ matrix.target.name }}
    if: always()
    needs: [builds, build-mod]
    strategy:
      matrix:
        target: ${{ fromJson(needs.builds.outputs.mods) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ matrix.target.name }}.zip
          delete-merged: true
          pattern: ${{ matrix.target.name }}-*
