---
name: Build mods

on:
  workflow_dispatch:
    inputs:
      mods:
        type: string
        description: mod names to build
  push:
    paths:
      - "sources/*"
    branches:
      - main
  pull_request:

jobs:
  builds:
    name: Get mods to build
    runs-on: ubuntu-latest
    outputs:
      mods: ${{ steps.builds.outputs.mods }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
      - name: Get changed files
        if: ${{ github.event_name }} == "push"
        id: changed_files_action
        uses: tj-actions/changed-files@v45
        with:
          files: sources/*
      - name: Get list of mods to build
        id: builds
        run: |
          # Figure out which manifests need building
          if [[ "${{ github.event_name }}" == "push" || "${{ github.event_name }}" == "pull_request" ]]; then
            export MODS="${{ steps.changed_files_action.outputs.all_changed_files }}"
          elif [[ "${{ inputs.mods }}" != "" ]]; then
            export MODS="${{ inputs.mods }}"
          fi
          echo "::group::Mods"
          echo "MODS=$(python3 get_mod_list.py)" >> $GITHUB_OUTPUT
          echo $MODS | jq
          echo "::endgroup::"

  build-mod: 
      needs: builds
      # strategy:
      #   matrix:
      #     target: ${{ fromJson(needs.builds.outputs.mods) }}
      uses: ./.github/workflows/build-mod.yml
      with:
        # target_name: ${{ matrix.target }}
        target_name: ctc

  merge-artifacts:
    name: Merge artifacts for ${{ matrix.target }}
    if: always()
    needs: [builds, build-mod]
    strategy:
      matrix:
        target: ${{ fromJson(needs.builds.outputs.mods) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Merge artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ matrix.target.name }}.zip
          pattern: ${{ matrix.target.name }}-*
          delete-merged: true
